### ISSUE TITLE
Crash Report 435089160

### ISSUE THREAD

**Issue by Adiaz0611** [wowsims/tbc#1070] opened 2022-06-25 04:51 UTC
runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 45 [running]:
runtime/debug.Stack(0xa0eab0, 0x4704a40, 0x40)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/tbc/sim/core.runSim.func1(0x64f5f80, 0x6e2a540)
	/home/runner/work/tbc/tbc/sim/core/sim.go:53 +0x8
panic(0x97b20, 0xa0eab0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:965 +0x19
github.com/wowsims/tbc/sim/core.NewTarget(0x0, 0x0, 0x0, 0x0, 0x0, 0x6112, 0x3a39d58, 0x8, 0x300000049, 0x6d5c600, ...)
	/home/runner/work/tbc/tbc/sim/core/target.go:132 +0x48
github.com/wowsims/tbc/sim/core.NewEncounter(0x0, 0x0, 0x0, 0x0, 0x0, 0x4072c00000000000, 0x403e000000000000, 0x3fc999999999999a, 0x0, 0x140c7d0, ...)
	/home/runner/work/tbc/tbc/sim/core/target.go:43 +0x14
github.com/wowsims/tbc/sim/core.(*Environment).construct(0x3b3cd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x474de00, 0x5, 0x8, 0x474de40, ...)
	/home/runner/work/tbc/tbc/sim/core/environment.go:48 +0x2
github.com/wowsims/tbc/sim/core.NewEnvironment(0x0, 0x0, 0x0, 0x0, 0x0, 0x474de00, 0x5, 0x8, 0x474de40, 0x4dfa620, ...)
	/home/runner/work/tbc/tbc/sim/core/environment.go:39 +0x3
github.com/wowsims/tbc/sim/core.NewSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4dfa5b0, 0x6e2a4e0, 0x474de80, 0x124a0003)
	/home/runner/work/tbc/tbc/sim/core/sim.go:111 +0x9
github.com/wowsims/tbc/sim/core.runSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4dfa5b0, 0x6e2a4e0, 0x474de80, 0x6e2a540, 0x6e2a300, ...)
	/home/runner/work/tbc/tbc/sim/core/sim.go:68 +0x2
github.com/wowsims/tbc/sim/core.RunSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4dfa5b0, 0x6e2a4e0, 0x474de80, 0x6e2a540, 0x0)
	/home/runner/work/tbc/tbc/sim/core/sim.go:39 +0x2
created by github.com/wowsims/tbc/sim/core.RunRaidSimAsync
	/home/runner/work/tbc/tbc/sim/core/api.go:74 +0x4

Request:
eJztUj1oFEEYvfftT2bHqMNGzHiN52FxBITdWw60MWshKmkEm5QJEmwCkZgiplokxkswcKS6XIqk0qskiMiJzZ0pjKYRtLgLgooSwUK0UtjzZ+aSI1ZRIYWF3/zw5n1v3jcDH9+w+bzNI/sa7PPDg1eHRhkTHckH4EJ8bULm3yFt12Lcegpuismm5us3SdbfbPLPY3AmVpTyxTTxLlFTuZWHSDuNGLXW5HvFjVmScQNpo9FSf4gh15TaFOvKr0vc+wz5akPdUepG2/L7N8gvL3XRxwUtnWlqfDuvcXmWlGJKFV1cxhZamNSZt9cp3V0hp0oUkZMnZ5XM12TVyRo3ep5R4n/sakyYDBJzuMAP8H0MApJSyKAfnsZwA0bCkkbGOk7jVgQrDyoARVhLwBKhDGMZRgVWFcYqrAKhSEja2iiDGRzO5jwv8HJe9phaCmd9dfD9IMgFvp/zSzjDBTfZ+09w2eaDToaa0W3SZo6GfD832PTBXwgtuX8X28w6EnxruJ2MiqAyEGIAvJNvZxJ/fnLVJ1KUoR7GcJb6lZNbMpxWtepoeKT92EOleR1Pet0mXZ57hAnWNzg8dPHSyJXUOfnvNuxYuCs2fuU3Pn075sd6T5/625In9BYtrIXtm+EAIiC5h1W6xeKPOx9tDz8Be76Lzw==

**Comment by jimmyt857** [comment] 2022-06-25 18:02
I believe this is a duplicate of #1066 which was fixed yesterday. Try refreshing your page!

**Closed** 2022-06-26 18:57 UTC
Labels: duplicate
