### ISSUE TITLE
Loading in from using the sim Defaults your Race.

### ISSUE THREAD

**Issue by Silversaviour** [wowsims/tbc#830] opened 2022-05-05 06:13 UTC
**Describe the bug**
Loading in a preset doesn't change your race. In my case I play night elf, which was displayed on the dropdown, but was using stats from draenei the most obvious of which was hit rating which was why I noticed.

**To Reproduce**
I honestly don't know what exactly caused it, I had opened the tab from the favorites to sim some new pieces I got and couldnt figure out why my hit rating was so high, I had changed my talents and reviewed the buffs page and saw nothing out of the ordinary I thought it was an issue with item stat numbers initially
**Expected behavior**
I expected the sim to show stats for the race displayed on the dropdown box.

**Sim Links and Screenshots**
I will attach some screenshots doing hit rating math that I had sent to a friend to help me figure out what I was doing wrong

![Maths](https://user-images.githubusercontent.com/104966398/166870963-011897b1-bc7c-4c00-8b62-91a2d38fd582.png)
![Buffsnstuff](https://user-images.githubusercontent.com/104966398/166870986-f89a50bb-3545-42c4-bc12-65b6f943a846.png)
![ingame gear](https://user-images.githubusercontent.com/104966398/166871000-f8ce719c-3a9e-4e9d-95fe-36936e8815a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home version 21H2
 - Browser: Microsoft Edge 
 - Version 101.0.1210.32 (Official build) (64-bit)

**Comment by jimmyt857** [comment] 2022-05-05 15:27
Could you send a link to your settings? (top right --> Export --> Link)

That will be a lot more helpful to investigate this.

**Comment by Silversaviour** [comment] 2022-05-05 19:20
https://wowsims.github.io/tbc/warrior/#eJztkj9LA0EQxfMml3A5FJaocKaKp4IKwt2FgFaunTYarFJYqGBQsNEqWgU1oIIgdongn29gJUJAgjaKBi0UEhAkIjaCEBuRJOreLeIXsHRgZ2d+j30zxWrURcEWFfugLiQpBe8xfHnQFiiU8y3DH5ubXJxeUP0sEMpBY6xWgb72BMOfqaNUhaaw60+Hr7xBL5YFL1TxKLjKrtKk366T1sS+xJuzHIxAydUcuZFtClgtwfAW3PZDtJfrZHgd0waWfZFWBdfqrgb94dkZUxLV+/2vprBK3cnFNIn84da7ZefNkTDcWSXNI8hpmgz1kJRzUpLenhvy/MefxpKqgkOnPiyMazEGXXylbimNcEsWHbzfvfNjfFCSZj4syRTPQKJFfiArvsdnMIE4toCgJ+TXEYaJDXRGoqZpRkwrErVNyxSNbVu94nawOFHbss1IFh5jNOAapRK87WdcazbjxMVA0JaicsLDwzoF25lYPwUMUYziYmySZhNuvA7MyxW3+TfVvnfO

hope this clears some things up.

**Comment by jimmyt857** [comment] 2022-05-11 05:13
Going to close this for now since I'm unable to reproduce and have not seen this happen to anyone else. Feel free to reopen if it occurs again.

**Closed by jimmyt857** 2022-05-11 05:13 UTC
