### ISSUE TITLE
Ashtongue Talisman of Insight (mage trinket, Ashtongue Deathsworn Exalted) doesn't apper to be working

### ISSUE THREAD

**Issue by Aussie-Scum** [wowsims/tbc#1082] opened 2022-07-06 06:21 UTC
**Describe the bug**
Doing some mage sims with trinkets.  When replacing Icon of the Silver Crescent with Ashtongue Talisman of Insight, simmed DPS goes DOWN by 20 DPS (which is not what I'd expect to see).  

**To Reproduce**
1. Go to Mage Sim
2. Click on P5 Arcane Presets
3. Replace Skull of Guldan with Icon of the Silver Crescent
4. Set Settings for +/- 20 executions
5. Run DPS for 10000 iterations
6. Comes to 2700 DPS
7. Replace Icon with Ashtongue Talisman
8. Run 10000 iterations
9. DPS comes to 2680
10. Check the Log.  There is no reference to any proc for Ashtong Talisman in the log

**Expected behavior**
Would expect to see a proc for 145 spell haste every now and then in the log.  Didn't see any.

**Sim Links and Screenshots**
I don't know that screenshots would add anything to this, the explanation above explains it pretty much.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102.0

**Additional context**
N/A

**Comment by jimmyt857** [comment] 2022-07-06 23:09
It looks like this is working as intended, except we had it marked as a spell instead of an item, so in the buffs menu it shows up as https://tbc.wowhead.com/spell=32488/stylin-crimson-hat instead of https://tbc.wowhead.com/item=32488/ashtongue-talisman-of-insight.

Will have a fix out for the UI issue soon. The dps difference is working as intended, though.

**Closed** 2022-07-06 23:12 UTC
