### ISSUE TITLE
Band of the Eternal Sage does not proc in simulation

### ISSUE THREAD

**Issue by clownburner** [wowsims/tbc#1042] opened 2022-06-17 22:06 UTC
The Band of the Eternal Sage has a spellpower proc that is not being reproduced in the sim, causing the item to sim worse than it actually is.

**To Reproduce**

1. Select Druid Balance P5 preset
2. Replace 1 ring with "Band of the eternal sage"
3. Run simulation
4. Check log for cast/buff effect "Band of the eternal sage"
5. Notice it is missing
6. make a sad face

**Comment by jimmyt857** [comment] 2022-06-18 22:45
Definitely works when I try it: https://wowsims.github.io/tbc/balance_druid/#eJzjYuFgVGByYuNglGBUYBTi4mDUYExgzGAsYJT6y9LEyBaQk1iZWsTBIcAodYWRS0DgcQ+TRPsTRiW2Nd1MR34zcrEIzOlmAopfB4pfewgUv/ubESTOK3Com0niXxOTEjOIKyxw+BOjxOHdjEqc138zAtFdsJq+XiaJtg2MSswbpoMMeQ405MMdoCFALSARToHfvXADfnYxSVzaCzTgCNgGkDyvQE8fk8TDyVA1HAI/nzBKdGwAsXYBjQKxWAQe/wWRf3uYgKILgKILwKLNQFcDyb+MStwbmBgbmJhPMDFWMGldYGIYBVQFVcCk5cAowGTEw8XCwSLAKMQgxcTF0MUoa2poYGBkZGxoZGpgbGhsagQiDHV1TY0MDIyNZzEyKH1l4gSb0JDmoAgxS8RBctZMEDhpL3SdScFTYthHGMs+B3pbCQD442Wj

You'll have to provide your settings if you're still having this issue.

**Comment by jimmyt857** [comment] 2022-06-25 00:32
Closing because OP hasn't responded and there is not a reproducible issue here.

**Closed by jimmyt857** 2022-06-25 00:32 UTC
