### ISSUE TITLE
Variable Encounter Length

### ISSUE THREAD

**Issue by triper99** [wowsims/tbc#127] opened 2021-12-27 22:12 UTC
**Is your feature request related to a problem? Please describe.**
Large fluctuations in DPS depending on small adjustments in length of encounter and no changes in items or buffs.  I'm pretty sure this is just due to a certain breakpoint being reached in the sim, and an extra spell is able to be cast before the encounter ends.  This can also be seen when adding a small amount of haste, pushing the cast time over the break point and adding additional DPS, when normally that amount of haste wouldn't be worth that much.

Cloak of the Illidari Council @ 270 seconds
<img width="1280" alt="Crit Cloak 270 Time" src="https://user-images.githubusercontent.com/96750659/147510186-4e50818e-3650-4ea1-8e6d-5b80b50194fd.png">

Shroud of the Highborne @ 270 seconds
<img width="1277" alt="Haste Cloak 270 Time" src="https://user-images.githubusercontent.com/96750659/147510202-e66fcf86-730c-416e-93ea-c6d6c23106a1.png">

Cloak of the Illidari Council @ 290 seconds
<img width="1280" alt="Crit Cloak 290 Time" src="https://user-images.githubusercontent.com/96750659/147510207-f0cbb867-55f0-4b7e-ae9d-b8c343e55302.png">

Shroud of the Highborne @ 290 seconds
<img width="1280" alt="Haste Cloak 290 Time" src="https://user-images.githubusercontent.com/96750659/147510209-b3af8d38-a7dd-42be-bf63-301aed5eeb68.png">

**Describe the solution you'd like**
An option to add a variable +/- amount of time to the encounter, to help average out results better, and to be more realistic to real-world DPS situations.

**Comment by jimmyt857** [comment] 2021-12-28 01:19
Hmmm, I think you're right that this is caused by a subtle breakpoint, but that's a really large DPS gap to just be encounter length. Are you using the adaptive rotation in these sims? Adaptive has a hard breakpoint based on how much mana is available, and if you're right on the edge it might give numbers like this.

**Comment by triper99** [comment] 2021-12-28 02:16
I am using adaptive rotations for those examples.

**Comment by jimmyt857** [comment] 2021-12-28 05:28
For now I think the best workaround is to use settings that are slightly more mana-friendly, and I would expect it to become more consistent. If you're hitting this case then more mana efficiency might be a dps boost anyway. You're also welcome to use other rotations if you value consistency over anything else, it just depends what you want from the sim. If changing the mana doesn't fix the consistency then please comment here (and probably link your sim settings too). A simple way to check would be to add ~20 mp5 as bonus stats.

Going to leave this thread open for now since it's a real bug. This one is going to be a challenge to fix though and we're pretty busy at the moment so it might be awhile before its fixed.

**Comment by lologarithm** [comment] 2022-03-18 15:28
This was implemented in January so I am closing the issue :)

**Closed by lologarithm** 2022-03-18 15:28 UTC
